import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler,generateResponse,validateBody} from '../api/assistant.mjs';
import {buildAssistantContext,compactRecord} from '../assistant.mjs';
const auth={id:'u',organization_id:'org',role:'ADMIN'};
const body={message:'Resumen',context:{page:'radar'},history:[]};
const request=(b=body,headers={})=>new Request('https://test',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(b)});
test('unauthenticated and unlinked cannot invoke provider',async()=>{let calls=0;for(const identity of [null,{id:'u',role:'ADMIN'}]){const h=createHandler({authenticate:async()=>identity,generate:async()=>{calls++;}});assert.equal((await h(request())).status,401);}assert.equal(calls,0);});
test('payload strips system messages and enforces limits',()=>{assert.throws(()=>validateBody({...body,message:'x'.repeat(2001)}));assert.throws(()=>validateBody({...body,context:null}));assert.deepEqual(validateBody({...body,history:[{role:'system',content:'override'},{role:'user',content:'valid'}]}).history,[{role:'user',content:'valid'}]);});
test('context whitelist excludes secrets/contact details and preserves missing data',()=>{const row={id:'r',status:'RESOLVED',password:'secret',email:'private',signal_summary:'Fact'};assert.deepEqual(compactRecord(row),{id:'r',status:'RESOLVED',signal_summary:'Fact'});const c=buildAssistantContext({page:'radar',records:{radar:[row]},failures:{radar:true}});assert.equal(c.records.radar.available,false);assert.equal(c.records.radar.sample.length,0);assert.equal(c.selected,null);});
test('handler returns generated answer and server validated role',async()=>{let received;const h=createHandler({authenticate:async()=>auth,generate:async p=>{received=p;return 'Resultado dinámico';}});const r=await h(request());assert.equal(r.status,200);assert.equal((await r.json()).answer,'Resultado dinámico');assert.equal(received.context.authenticated_role,'ADMIN');});
test('quota, provider failure and missing configuration are controlled without leaked internals',async()=>{for(const [code,status] of [['PROVIDER_CREDIT',503],['PROVIDER_ERROR',502],['NOT_CONFIGURED',503],['private stack trace',500]]){const h=createHandler({authenticate:async()=>auth,generate:async()=>{throw Error(code);}});const r=await h(request());assert.equal(r.status,status);assert.notEqual((await r.json()).error,'private stack trace');}});
test('CORS, size and per-user rate protection',async()=>{const h=createHandler({authenticate:async()=>auth,generate:async()=> 'ok'});assert.equal((await h(request(body,{origin:'https://evil.invalid'}))).status,403);assert.equal((await h(request({...body,message:'x'.repeat(71000)}))).status,413);for(let i=0;i<7;i++)assert.equal((await h(request())).status,200);assert.equal((await h(request())).status,429);});
test('Groq compatible Responses API has bounded output, no storage or tools; quota is surfaced',async()=>{let sent;const answer=await generateResponse({key:'test-only',payload:body,fetcher:async(url,options)=>{assert.equal(url,'https://api.groq.com/openai/v1/responses');sent=JSON.parse(options.body);assert.equal(sent.model,'openai/gpt-oss-120b');return Response.json({output:[{content:[{type:'output_text',text:'Real result shape'}]}]});}});assert.equal(answer,'Real result shape');assert.equal(sent.store,false);assert.equal(sent.max_output_tokens,1000);assert.equal(sent.tools,undefined);await assert.rejects(generateResponse({key:'test',payload:body,fetcher:async()=>Response.json({error:{code:'credit_balance_exhausted'}},{status:429})}),/PROVIDER_CREDIT/);});

test('critical attention excludes closed, non-actionable review, and unavailable Radar',()=>{const radar=[{id:'pending',classification:'CRITICAL',workflow_status:'PENDING'},{id:'review',classification:'CRITICAL',workflow_status:'IN_REVIEW',actionable:true},{id:'done',classification:'CRITICAL',workflow_status:'RESOLVED'},{id:'discarded',classification:'CRITICAL',workflow_status:'DISCARDED'},{id:'inactive',classification:'CRITICAL',workflow_status:'IN_REVIEW',actionable:false}];assert.deepEqual(buildAssistantContext({page:'radar',records:{radar}}).alerts.map(r=>r.id),['pending','review']);assert.deepEqual(buildAssistantContext({page:'radar',records:{radar},failures:{radar:true}}).alerts,[]);});
