import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemoHandler,DEMO} from '../api/conversations-dev-demo.mjs';
const env={VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:DEMO.branch,CONVERSATIONS_DEV_ENABLED:'true',CONVERSATIONS_SUPABASE_URL:'https://rmximatxuaczhpqbcuho.supabase.co',CONVERSATIONS_SERVICE_KEY:'sb_secret_test',CONVERSATIONS_TEST_ORG_ID:DEMO.org,CONVERSATIONS_TEST_CONTACT_ID:DEMO.contact,CONVERSATIONS_TEST_OWNER_ID:DEMO.owner};
const c={id:DEMO.conversation,organization_id:DEMO.org,contact_id:DEMO.contact,owner_user_id:DEMO.owner,revision:1};
function fixture(overrides={}){let commands=[];let reads=[];const handle=createDemoHandler({env:{...env,...overrides},fetcher:async(url,options)=>{reads.push(url);assert.equal(options.headers.apikey,'sb_secret_test');if(url.includes('/profiles?'))return Response.json([{id:DEMO.owner,organization_id:DEMO.org,role:'ADMIN'}]);if(url.includes('/commercial_conversations?'))return Response.json([c]);return Response.json([]);},store:{command:async(...args)=>{commands.push(args);return {ok:true};}}});return {handle,commands,reads};}
const get=(id=DEMO.conversation,origin=DEMO.origin)=>new Request(origin+'/api/conversations-dev-demo?id='+id);
const post=(data,headers={})=>new Request(DEMO.origin+'/api/conversations-dev-demo',{method:'POST',headers:{origin:DEMO.origin,'content-type':'application/json',...headers},body:JSON.stringify({action:'update',data:{conversation_id:DEMO.conversation,revision:1,owner_id:DEMO.owner,status:'active',next_action:'Prueba',follow_up_at:'2026-10-10T18:00:00Z',...data}})});
test('reads only the fixed synthetic case, never returns credentials',async()=>{const f=fixture();const r=await f.handle(get());assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert(!JSON.stringify(await r.json()).includes('sb_secret'));assert(f.reads.every(u=>u.includes(DEMO.conversation)||u.includes(DEMO.owner)));});
for(const [name,override] of [['production',{VERCEL_ENV:'production'}],['wrong branch',{VERCEL_GIT_COMMIT_REF:'main'}],['wrong project',{CONVERSATIONS_SUPABASE_URL:'https://other.supabase.co'}],['wrong contact',{CONVERSATIONS_TEST_CONTACT_ID:'other'}],['wrong owner',{CONVERSATIONS_TEST_OWNER_ID:'other'}],['disabled',{CONVERSATIONS_DEV_ENABLED:'false'}]])test('blocks '+name,async()=>{const f=fixture(override);assert.equal((await f.handle(get())).status,403);assert.equal(f.reads.length,0);});
test('blocks other hosts',async()=>{const f=fixture();assert.equal((await f.handle(get(DEMO.conversation,'https://xicronix-commercial-intelligence.vercel.app'))).status,403);});
test('blocks other conversation IDs',async()=>{const f=fixture();assert.equal((await f.handle(get('00000000-0000-4000-8000-000000000001'))).status,403);});
test('blocks cross-origin writes',async()=>{const f=fixture();assert.equal((await f.handle(post({}, {origin:'https://evil.example'}))).status,403);assert.equal(f.commands.length,0);});
test('blocks changing owner',async()=>{const f=fixture();assert.equal((await f.handle(post({owner_id:'00000000-0000-4000-8000-000000000001'}))).status,403);assert.equal(f.commands.length,0);});
test('blocks opportunity or extra fields',async()=>{const f=fixture();assert.equal((await f.handle(post({opportunity_id:'00000000-0000-4000-8000-000000000001'}))).status,403);assert.equal(f.commands.length,0);});
test('synthetic updates use existing SQL command',async()=>{const f=fixture();assert.equal((await f.handle(post({}))).status,200);assert.equal(f.commands.length,1);assert.equal(f.commands[0][0],DEMO.org);assert.equal(f.commands[0][1],DEMO.owner);assert.equal(f.commands[0][2],'update');});
test('fails closed on unavailable storage',async()=>{const handle=createDemoHandler({env,fetcher:async()=>new Response('no',{status:503})});assert.equal((await handle(get())).status,503);});

